-- Borra todo lo creado por 01-09. Correr bloque por bloque, no "Run All".
USE ROLE ACCOUNTADMIN;

-- Apagar el DAG: raiz primero.
ALTER TASK IF EXISTS LIBRARY_DW.BOOK_REVIEWS.TASK_INGEST_S3     SUSPEND;
ALTER TASK IF EXISTS LIBRARY_DW.BOOK_REVIEWS.TASK_FLATTEN_REVIEWS SUSPEND;

-- Quitar masking antes de borrar lo que protege.
ALTER TABLE IF EXISTS LIBRARY_DW.RAW.USERS MODIFY COLUMN phone UNSET MASKING POLICY;
ALTER TABLE IF EXISTS LIBRARY_DW.RAW.USERS MODIFY COLUMN email UNSET MASKING POLICY;
DROP MASKING POLICY IF EXISTS LIBRARY_DW.RAW.mask_phone;
DROP MASKING POLICY IF EXISTS LIBRARY_DW.RAW.mask_email;

DROP ROLE IF EXISTS ROLE_DATA_ENGINEER;
DROP ROLE IF EXISTS ROLE_DATA_ANALYST;
DROP ROLE IF EXISTS ROLE_BUSINESS_MANAGER;
DROP ROLE IF EXISTS ROLE_PASANTE;
DROP ROLE IF EXISTS LIBRARY_LOADER;

-- CASCADE arrastra esquemas, tablas, stage, file format y tasks.
DROP DATABASE IF EXISTS LIBRARY_DW CASCADE;
DROP WAREHOUSE IF EXISTS WH_LIBRARY;

-- Debe salir todo vacio.
SHOW WAREHOUSES LIKE 'WH_LIBRARY';
SHOW DATABASES LIKE 'LIBRARY_DW';
SHOW ROLES LIKE 'ROLE_%';
SHOW ROLES LIKE 'LIBRARY_LOADER';
