-- Arquitectura Snowflake como codigo, proyecto biblioteca
-- rol de servicio. Base para la ingesta desde Neon.

USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE IF NOT EXISTS WH_LIBRARY
    WAREHOUSE_SIZE      = 'XSMALL'
    AUTO_SUSPEND        = 60
    AUTO_RESUME         = TRUE
    INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS LIBRARY_DW;

CREATE SCHEMA IF NOT EXISTS LIBRARY_DW.RAW
    COMMENT = 'Datos relacionales desde Neon (Flyway), sin transformar';

-- Rol de servicio, sin privilegios de administracion.
CREATE ROLE IF NOT EXISTS LIBRARY_LOADER;

GRANT USAGE ON WAREHOUSE WH_LIBRARY TO ROLE LIBRARY_LOADER;
GRANT USAGE ON DATABASE LIBRARY_DW TO ROLE LIBRARY_LOADER;
GRANT USAGE, CREATE TABLE ON SCHEMA LIBRARY_DW.RAW TO ROLE LIBRARY_LOADER;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA LIBRARY_DW.RAW TO ROLE LIBRARY_LOADER;

GRANT ROLE LIBRARY_LOADER TO USER SHIGUITAU1030;

-- Verificacion
SHOW WAREHOUSES LIKE 'WH_LIBRARY';
SHOW SCHEMAS IN DATABASE LIBRARY_DW;
SHOW GRANTS TO ROLE LIBRARY_LOADER;
