-- Fix del schema drift detectado en AUTHORS.

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE WH_LIBRARY;
USE DATABASE LIBRARY_DW;
USE SCHEMA RAW;

ALTER TABLE AUTHORS ADD COLUMN "WEBSITE" VARCHAR;

DESCRIBE TABLE AUTHORS;