USE ROLE ACCOUNTADMIN;
USE WAREHOUSE WH_LIBRARY;
USE DATABASE LIBRARY_DW;

CREATE SCHEMA IF NOT EXISTS BOOK_REVIEWS;

CREATE OR REPLACE FILE FORMAT FF_BOOK_REVIEWS_JSON
    TYPE=JSON
    STRIP_OUTER_ARRAY=TRUE;

USE SCHEMA BOOK_REVIEWS;

CREATE OR REPLACE STAGE STG_BOOK_REVIEWS_S3
    URL='s3://my-s3-bucket'
    FILE_FORMAT=FF_BOOK_REVIEWS_JSON;

-- Validate
LIST @STG_BOOK_REVIEWS_S3;