USE ROLE ACCOUNTADMIN;
USE WAREHOUSE WH_LIBRARY;
USE DATABASE LIBRARY_DW;
USE SCHEMA BOOK_REVIEWS;

CREATE TABLE IF NOT EXISTS RAW_REVIEWS (
    raw_data       VARIANT,
    _stg_file_name STRING,
    _stg_loaded_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

COPY INTO RAW_REVIEWS (raw_data, _stg_file_name, _stg_loaded_at)
FROM (
    SELECT $1, METADATA$FILENAME, CURRENT_TIMESTAMP()
    FROM @STG_BOOK_REVIEWS_S3
)
FILE_FORMAT=(FORMAT_NAME=FF_BOOK_REVIEWS_JSON)
ON_ERROR = ABORT_STATEMENT;

-- Validate
SELECT * FROM RAW_REVIEWS;
