USE ROLE ACCOUNTADMIN;
USE WAREHOUSE WH_LIBRARY;
USE DATABASE LIBRARY_DW;
USE SCHEMA RAW;

CREATE ROLE IF NOT EXISTS ROLE_DATA_ENGINEER
    COMMENT = 'Opera el pipeline, necesita ver todo RAW para depurar drift y cargas';
CREATE ROLE IF NOT EXISTS ROLE_DATA_ANALYST
    COMMENT = 'Analiza catalogo, usuarios y prestamos; sin acceso a multas ni a personal';
CREATE ROLE IF NOT EXISTS ROLE_BUSINESS_MANAGER
    COMMENT = 'Consume reportes de usuarios; sin acceso a catalogo, prestamos ni multas';

GRANT USAGE ON WAREHOUSE WH_LIBRARY TO ROLE ROLE_DATA_ENGINEER;
GRANT USAGE ON WAREHOUSE WH_LIBRARY TO ROLE ROLE_DATA_ANALYST;
GRANT USAGE ON WAREHOUSE WH_LIBRARY TO ROLE ROLE_BUSINESS_MANAGER;

GRANT USAGE ON DATABASE LIBRARY_DW TO ROLE ROLE_DATA_ENGINEER;
GRANT USAGE ON DATABASE LIBRARY_DW TO ROLE ROLE_DATA_ANALYST;
GRANT USAGE ON DATABASE LIBRARY_DW TO ROLE ROLE_BUSINESS_MANAGER;

GRANT USAGE ON SCHEMA RAW TO ROLE ROLE_DATA_ENGINEER;
GRANT USAGE ON SCHEMA RAW TO ROLE ROLE_DATA_ANALYST;
GRANT USAGE ON SCHEMA RAW TO ROLE ROLE_BUSINESS_MANAGER;

-- Data Engineer: acceso completo a RAW (depuracion de pipeline y drift)
GRANT SELECT ON ALL TABLES IN SCHEMA RAW TO ROLE ROLE_DATA_ENGINEER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA RAW TO ROLE ROLE_DATA_ENGINEER;

-- Data Analyst: catalogo, usuarios y prestamos. Sin PENALTIES (financiero)
-- ni LIBRARIANS (datos de personal).
GRANT SELECT ON TABLE USERS      TO ROLE ROLE_DATA_ANALYST;
GRANT SELECT ON TABLE LOANS      TO ROLE ROLE_DATA_ANALYST;
GRANT SELECT ON TABLE COPIES     TO ROLE ROLE_DATA_ANALYST;
GRANT SELECT ON TABLE EDITIONS   TO ROLE ROLE_DATA_ANALYST;
GRANT SELECT ON TABLE BOOKS      TO ROLE ROLE_DATA_ANALYST;
GRANT SELECT ON TABLE AUTHORS    TO ROLE ROLE_DATA_ANALYST;
GRANT SELECT ON TABLE CATEGORIES TO ROLE ROLE_DATA_ANALYST;

-- Business Manager: solo la tabla de usuarios, para reportes.
GRANT SELECT ON TABLE USERS TO ROLE ROLE_BUSINESS_MANAGER;

GRANT ROLE ROLE_DATA_ENGINEER    TO USER SHIGUITAU1030;
GRANT ROLE ROLE_DATA_ANALYST     TO USER SHIGUITAU1030;
GRANT ROLE ROLE_BUSINESS_MANAGER TO USER SHIGUITAU1030;

-- Antes de aplicar masking, ROLE_DATA_ENGINEER ve el dato sin proteger.
USE ROLE ROLE_DATA_ENGINEER;
USE SECONDARY ROLES NONE;
SELECT name, email, phone FROM RAW.USERS ORDER BY name;

USE ROLE ACCOUNTADMIN;
USE SECONDARY ROLES ALL;
