USE ROLE ACCOUNTADMIN;
USE WAREHOUSE WH_LIBRARY;
USE DATABASE LIBRARY_DW;
USE SCHEMA RAW;

CREATE OR REPLACE MASKING POLICY mask_phone AS (val STRING) RETURNS STRING ->
    CASE
        WHEN CURRENT_ROLE() = 'ROLE_DATA_ENGINEER' THEN val
        WHEN CURRENT_ROLE() = 'ROLE_DATA_ANALYST'  THEN CONCAT(LEFT(val, 6), '-****')
        ELSE '***-***-****'
    END;

CREATE OR REPLACE MASKING POLICY mask_email AS (val STRING) RETURNS STRING ->
    CASE
        WHEN CURRENT_ROLE() = 'ROLE_DATA_ENGINEER' THEN val
        ELSE '*** email protegido ***'
    END;

ALTER TABLE USERS MODIFY COLUMN phone SET MASKING POLICY mask_phone;
ALTER TABLE USERS MODIFY COLUMN email SET MASKING POLICY mask_email;

-- Verificar que las politicas quedaron atadas
SHOW MASKING POLICIES;

SELECT *
FROM TABLE(INFORMATION_SCHEMA.POLICY_REFERENCES(
    REF_ENTITY_NAME => 'LIBRARY_DW.RAW.USERS',
    REF_ENTITY_DOMAIN => 'TABLE'
));

-- Ve TODO
USE ROLE ROLE_DATA_ENGINEER;
SELECT name, email, phone FROM USERS ORDER BY name;

-- Ve el telefono PARCIAL, y el email oculto
USE ROLE ROLE_DATA_ANALYST;
SELECT name, email, phone FROM USERS ORDER BY name;

-- No ve NADA sensible
USE ROLE ROLE_BUSINESS_MANAGER;
SELECT name, email, phone FROM USERS ORDER BY name;

USE ROLE ACCOUNTADMIN;

-- Caso del ELSE: un rol NO nombrado en la politica tambien queda protegido
CREATE ROLE IF NOT EXISTS ROLE_PASANTE
    COMMENT = 'Rol de prueba, no mencionado en la masking policy, para demostrar default-deny';
GRANT USAGE ON WAREHOUSE WH_LIBRARY TO ROLE ROLE_PASANTE;
GRANT USAGE ON DATABASE LIBRARY_DW TO ROLE ROLE_PASANTE;
GRANT USAGE ON SCHEMA RAW TO ROLE ROLE_PASANTE;
GRANT SELECT ON TABLE USERS TO ROLE ROLE_PASANTE;
GRANT ROLE ROLE_PASANTE TO USER SHIGUITAU1030;

USE ROLE ROLE_PASANTE;
SELECT name, email, phone FROM USERS ORDER BY name;  -- cae en el ELSE, sin cambiar la politica

USE ROLE ACCOUNTADMIN;