USE ROLE ACCOUNTADMIN;

-- Arquitectura
SHOW WAREHOUSES LIKE 'WH_LIBRARY';
SHOW SCHEMAS IN DATABASE LIBRARY_DW;
SHOW GRANTS TO ROLE LIBRARY_LOADER;

-- Ingesta relacional
SHOW TABLES IN SCHEMA LIBRARY_DW.RAW;
DESCRIBE TABLE LIBRARY_DW.RAW.AUTHORS;

-- Ingesta semi-estructurada
SHOW FILE FORMATS IN SCHEMA LIBRARY_DW.BOOK_REVIEWS;
SHOW STAGES IN SCHEMA LIBRARY_DW.BOOK_REVIEWS;
LIST @LIBRARY_DW.BOOK_REVIEWS.STG_BOOK_REVIEWS_S3;
DESCRIBE TABLE LIBRARY_DW.BOOK_REVIEWS.RAW_REVIEWS;
SELECT (SELECT COUNT(*) FROM LIBRARY_DW.BOOK_REVIEWS.RAW_REVIEWS)              AS libros,
       (SELECT COUNT(*) FROM LIBRARY_DW.BOOK_REVIEWS.STG_BOOK_REVIEWS_FLATTENED) AS filas_resenas;

-- Tasks
SHOW TASKS IN SCHEMA LIBRARY_DW.BOOK_REVIEWS;
SELECT name, state, scheduled_time, completed_time, error_message
FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY())
ORDER BY scheduled_time DESC
LIMIT 20;

-- RBAC + masking
SHOW ROLES LIKE 'ROLE_%';
SHOW MASKING POLICIES;
SELECT *
FROM TABLE(INFORMATION_SCHEMA.POLICY_REFERENCES(
    REF_ENTITY_NAME => 'LIBRARY_DW.RAW.USERS',
    REF_ENTITY_DOMAIN => 'TABLE'
));
